stages:
  - build

# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_BUILDKIT: "1"
  BUILDKIT_PROGRESS: "plain"
  SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY # base64 encoded

default:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker info

    # https://docs.gitlab.com/ee/ci/ssh_keys/
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh

    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add -
    - chmod 700 ~/.ssh

    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY


build:
  stage: build
  variables:
    IMAGE_NAME_BASE: "registry.gitlab.com/ksu_evt/autonomous-software/voltron_ws"
  script:
    - IMAGE_BASE="$IMAGE_NAME_BASE/ros-base"
    - IMAGE_DEV="$IMAGE_NAME_BASE/ros-dev"
    - BASE_TAGS="-t $IMAGE_BASE:$CI_COMMIT_SHORT_SHA"
    - DEV_TAGS="-t $IMAGE_DEV:$CI_COMMIT_SHORT_SHA"
    - if [[ $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ]]; then BASE_TAGS="$BASE_TAGS -t $IMAGE_BASE:latest -t $IMAGE_BASE:humble"; fi
    - if [[ $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ]]; then DEV_TAGS="$DEV_TAGS -t $IMAGE_DEV:latest -t $IMAGE_DEV:humble"; fi
    - docker build --ssh default $BASE_TAGS -f .docker/base.Dockerfile .
    - docker build --ssh default $DEV_TAGS -f .docker/dev.Dockerfile .
    - docker push --all-tags $IMAGE_BASE
    - docker push --all-tags $IMAGE_DEV
