gantt
    title Autonomous timeline (v3)
    dateFormat  YYYY-MM-DD
    axisFormat  %y-%m-%d
    section Software
    (ON HOLD)Micro-Ros platformio port :2022-08-21, 60d
    Voltron Simulator refresh :2022-08-04, 30d
    paper : 2022-8-26, 7d
    orientation fix RTK gps : rtk, 2022-8-26, 2d
    VNC local dev env. bringup : vnc-local, 2022-8-26, 7d
    Voltron mpc tuning : mpc, after rtk, 30d
    
    VNC remote dev env. bringup : after vnc-local, 15d

    

    
    GTSAM SLAM : slam, after mpc, 60d

    cone detection: cd, after mpc, 30d
    multi-kart simulator : after mpc, 30d
    Ground Speed Sensor   :gss, after cd, 60d
    
    GSS Simulator : gss-sim, after cd, 15d
    
    Localization sensor fusion : sf, after cd, 120d
    

    kart detection: d4, after gss, 60d


    
    
    

    f1-tenth : 2022-09-25, 5d

    multi-kart senior project : 2022-12-01, 120d
    
    %% embedded hybrid
    ibooster testing :2022-09-09, 15d
    PC Batt BMS (ennoid) inte. :2022-08-26, 15d
    Odrive-PRO integration : 2022-10-01, 30d
    CPLD bringup :se1, 2022-10-01, 30d
    SCU bringup : after se1, 30d


    section Electrical
    f1-tenth : 2022-09-25, 5d

    %% embedded hybrid
    ibooster testing :2022-09-09, 15d
    PC Batt BMS (ennoid) inte. :e1, 2022-09-01, 15d
    Odrive-PRO integration : e2, 2022-10-01, 30d
    CPLD bringup :e3, 2022-10-01, 30d
    SCU bringup : after e3, 30d

    electrical re-design : e1, 2022-08-04, 150d
    harness re-make: after e1, 20d
    

    section Mechanical
    f1-tenth : 2022-09-25, 5d

    iBooster integration : m1, 2022-08-15, 30d
    steering study : m2, after m1, 30d
    steering refresh : after m2, 30d
    mounting new PC : m3, 2022-09-01, 30d
    new PC battery box : m4, after m3, 30d
    main electronics box : 2022-12-01, 20d